CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	external_id TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	apikey TEXT NOT NULL UNIQUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS urls (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	creator INTEGER NOT NULL,
	url TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (creator) REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION
);

